version: "3.4"

services:
  orangescrum-be:
    image: rbekker87/orangescrum:v6
    networks:
      - appnet
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=orangescrum_db
      - SENDGRID_HOSTNAME=smtp.sendgrid.net
      - SENDGRID_PORT=587
      - SENDGRID_KEY=apikey
      - SENDGRID_SECRET=apisecret
      - APP_FQDN=projects.domain.com
      - APP_NOTIFIER_EMAIL=notify@domain.com
      - APP_SUPPORT_EMAIL=support@domain.com
      - APP_DEV_EMAIL=developer-support@domain.com
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.10'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 32M

  orangescrum:
    image: rbekker87/nginx-proxy:alpine
    networks:
      - appnet
    environment:
      - UPSTREAM_NAME=orangescrum-be
      - UPSTREAM_PORT=80
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.backend.loadbalancer.sticky=false"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.backend=orangescrum"
        - "traefik.docker.network=appnet"
        - "traefik.entrypoints=https"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.rule=Host:projects.domain.com"
        - "traefik.port=80"
      resources:
        limits:
          cpus: '0.10'
          memory: 32M
        reservations:
          cpus: '0.10'
          memory: 16M
networks:
  appnet:
    external: true
